### ISSUE TITLE
Image sizing incorrect on /touchToBegin

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#364]
![image](https://user-images.githubusercontent.com/737638/71780092-39204600-2ff9-11ea-9ed3-44321ab88f49.png)

**Comment by kennyviperhk** [comment]
fixed in #373 
The logo somehow has stopped spinning. is it normal?
should we make it spin again?

**Comment by dhowe** [comment]
yes, should spin on the first page

**Comment by dhowe** [comment]
Not sure why, but I still see the image in the wrong place with dev-tools on chrome (though icon is now spinning):


![image](https://user-images.githubusercontent.com/737638/72546839-740e5d80-38c6-11ea-9789-594c0a5faac3.png)

**Comment by dhowe** [comment]
and on other pages (how are you creating your device profile ? )

![image](https://user-images.githubusercontent.com/737638/72547414-92c12400-38c7-11ea-87fc-6ad316af82b7.png)

**Comment by kennyviperhk** [comment]
should be fixed now
